#!/bin/bash

## Prefer a single file to rule them all.

. bashrc
bash_setup
git_setup
echo run regedit /s solarized-dark.reg to solarize

#echo "bash should now be setup, restart a terminal to confirm"
